# Generated by Django 2.1.7 on 2019-04-01 16:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentBankAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=512)),
                ('bank_branch_name', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='ExpenseType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expense_type', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flat_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyCollections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField()),
                ('amount', models.FloatField(default=0)),
                ('payment_mode', models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=32)),
                ('cheque_date', models.DateField(default=datetime.date.today)),
                ('cheque_number', models.IntegerField(default=0)),
                ('cheque_bank_name', models.CharField(default='', max_length=512)),
                ('dep_bank_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerofloor.ApartmentBankAccounts')),
                ('flat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerofloor.Flat')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_data', models.CharField(max_length=200)),
                ('added_on', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthlyExpenses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('date_of_expenditure', models.DateField()),
                ('expenses_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zerofloor.ExpenseType')),
                ('month_details_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zerofloor.MonthlyDetails')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='monthlycollections',
            name='month_details_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zerofloor.MonthlyDetails'),
        ),
    ]
