# Generated by Django 2.1.7 on 2019-04-01 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerofloor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthlycollections',
            name='cheque_bank_name',
            field=models.CharField(default='abc', max_length=512),
        ),
        migrations.AlterField(
            model_name='monthlycollections',
            name='dep_bank_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zerofloor.ApartmentBankAccounts'),
        ),
    ]
