# Generated by Django 2.1.7 on 2019-04-04 17:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zerofloor', '0002_auto_20190401_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(max_length=512)),
                ('vendor_other_details', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='monthlyexpenses',
            name='cheque_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='monthlyexpenses',
            name='cheque_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyexpenses',
            name='dep_bank_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zerofloor.ApartmentBankAccounts'),
        ),
        migrations.AddField(
            model_name='monthlyexpenses',
            name='payment_mode',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Cheque', 'Cheque')], default='Cash', max_length=32),
        ),
        migrations.AddField(
            model_name='monthlyexpenses',
            name='vendor_info',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='zerofloor.VendorDetails'),
            preserve_default=False,
        ),
    ]
